import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { cn } from "@/ui/utils"
import { NEXT_PUBLIC_APP_NAME } from "@/env"

const inter = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}
